AWSTemplateFormatVersion: 2023-09-09
Description: |
  This temp launches an ec2 instance with a SG which enables SSH.
  
Resources:
  MYInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09239b9a6b1c06843
      InstanceType: t2.micro
      KeyName: firstkey1 # Please use your key pair name without pem.
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: First-MY-Instance
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          yum install git -y 
          cd /home/ec2-user
          git clone https://github.com/yeditepe0123/project_kitten_cfn.git
          cd
          cd /var/www/html
          chmod -R 777 /var/www/html/
          cp /home/ec2-user/Project-101-kittens-carousel-static-website-ec2/static-web/* .   
          systemctl restart httpd
          systemctl enable httpd 
  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH + HTTP + HTTPS for MYInstance # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      
