
AWSTemplateFormatVersion: '2010-09-09'
Description: Apache Web Server with SSL/TLS Configuration

# Use public Systems Manager Parameter
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId  # Latest AMI
      InstanceType: t2.micro  # EC2 Örnek Türünüzü buraya ekleyin
      KeyName: firstkey1  # Key Pair adınızı buraya ekleyin
      SecurityGroups:
        - !Ref MySecurityGroup  # Aşağıda tanımlanan güvenlik grubuna referans
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd mod_ssl
          systemctl start httpd
          systemctl enable httpd
          sudo wget https://github.com/yeditepe0123/Project-101-kittens-carousel-static-website-ec2/raw/main/static-web/index.html -O /var/www/html/index.html
          sudo wget https://github.com/yeditepe0123/Project-101-kittens-carousel-static-website-ec2/raw/main/static-web/cat0.jpg -O /var/www/html/cat0.jpg
          sudo wget https://github.com/yeditepe0123/Project-101-kittens-carousel-static-website-ec2/raw/main/static-web/cat1.jpg -O /var/www/html/cat1.jpg
          sudo wget https://github.com/yeditepe0123/Project-101-kittens-carousel-static-website-ec2/raw/main/static-web/cat2.jpg -O /var/www/html/cat2.jpg
          sudo wget https://github.com/yeditepe0123/Project-101-kittens-carousel-static-website-ec2/raw/main/static-web/cat3.png -O /var/www/html/cat3.png
          sudo systemctl start httpd
          sudo systemctl enable httpd

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP, SSH, and HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi

Outputs:
  WebsiteURL:
    Description: Web sayfasının URL'si
    Value: !Sub "https://${MyEC2Instance.PublicDnsName}/"
