AWSTemplateFormatVersion: '2010-09-09'
Description: Apache Web Server with SSL/TLS Configuration

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f409bae3775dc8e5  # Kullandığınız AMI-ID'yi buraya ekleyin
      InstanceType: t2.micro  # EC2 Örnek Türünüzü buraya ekleyin
      KeyName: firstkey1  # Key Pair adınızı buraya ekleyin
      SecurityGroups:
        - !Ref MySecurityGroup  # Aşağıda tanımlanan güvenlik grubuna referans
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd mod_ssl
          service httpd start
          chkconfig httpd on
          wget -O /etc/pki/tls/private/server.key https://your-key-url/server.key  # Özel anahtarınızın URL'sini buraya ekleyin
          wget -O /etc/pki/tls/certs/server.crt https://your-cert-url/server.crt  # SSL/TLS sertifikanızın URL'sini buraya ekleyin
          wget -O /etc/httpd/conf.d/ssl.conf https://your-ssl-config-url/ssl.conf  # SSL/TLS yapılandırma dosyanızın URL'sini buraya ekleyin
          systemctl start httpd
          systemctl enable httpd

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP, SSH, and HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Ev ağınızın IP adresi

Outputs:
  WebsiteURL:
    Description: Web sayfasının URL'si
    Value: !Sub "https://${MyEC2Instance.PublicDnsName}/"
